(function(){
  var KEY='phoenix_review_app_v14_data';
  var LEGACY_KEYS=['phoenix_review_app_v13_data','phoenix_review_app_v12_data','phoenix_review_app_v11_data','phoenix_review_app_v1_data'];
  var LEGACY_FORM_PREFIXES=['phoenix_review_app_v13_form_','phoenix_review_app_v12_form_','phoenix_review_app_v11_form_','phoenix_review_app_v1_form_'];
  var state={records:[],drafts:[],settings:{version:'1.4.7'}};
  var currentMode='review', currentDraftId=null, mood=3, energy=3, selectedTags=[];
  var timer=null;
  function $(id){return document.getElementById(id)}
  function qsa(sel){return Array.prototype.slice.call(document.querySelectorAll(sel))}
  function today(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
  function nowTime(){var d=new Date();return String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')}
  function stamp(){return new Date().toISOString()}
  function uid(p){return p+'_'+Date.now()+'_'+Math.random().toString(16).slice(2)}
  function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function nl(v){return (v||'').trim()||'未填写'}
  function toast(msg){var t=$('toast');if(!t){alert(msg);return}t.textContent=msg;t.classList.add('show');setTimeout(function(){t.classList.remove('show')},1800)}
  function okLS(){try{localStorage.setItem('__px_test','1');localStorage.removeItem('__px_test');return true}catch(e){return false}}
  function readJSON(k,fb){try{var x=localStorage.getItem(k);return x?JSON.parse(x):fb}catch(e){return fb}}
  function writeJSON(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch(e){console.warn(e);return false}}
  function download(filename,text,type){var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:type||'text/plain'}));a.download=filename;document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(a.href);document.body.removeChild(a)},120)}
  function copyText(txt){if(navigator.clipboard&&window.isSecureContext){navigator.clipboard.writeText(txt).then(function(){toast('已复制')}).catch(function(){fallbackCopy(txt)})}else fallbackCopy(txt)}
  function fallbackCopy(txt){var ta=document.createElement('textarea');ta.value=txt;ta.style.position='fixed';ta.style.left='-9999px';document.body.appendChild(ta);ta.focus();ta.select();try{document.execCommand('copy');toast('已复制')}catch(e){toast('复制失败，文本已生成')}document.body.removeChild(ta)}
  function normalize(data){data=data||{};var out={records:Array.isArray(data.records)?data.records:[],drafts:Array.isArray(data.drafts)?data.drafts:[],settings:data.settings||{version:'1.4'}};out.records=out.records.map(function(x){x=x||{};return {id:x.id||uid('rec'),type:x.type||'review',date:x.date||today(),time:x.time||((x.uploadedAt||x.createdAt||'').slice(11,16))||nowTime(),mood:Number(x.mood)||3,energy:Number(x.energy)||3,tags:Array.isArray(x.tags)?x.tags:[],thoughtType:x.thoughtType||x.typeLabel||x.thought_type||'行动线索',fields:x.fields||{},createdAt:x.createdAt||x.uploadedAt||stamp(),uploadedAt:x.uploadedAt||x.createdAt||stamp(),sourceDraftId:x.sourceDraftId||null}});out.drafts=out.drafts.map(function(x){x=x||{};return {id:x.id||uid('draft'),type:x.type||'review',date:x.date||today(),time:x.time||nowTime(),mood:Number(x.mood)||3,energy:Number(x.energy)||3,tags:Array.isArray(x.tags)?x.tags:[],thoughtType:x.thoughtType||'行动线索',fields:x.fields||{},status:x.status||'draft',createdAt:x.createdAt||stamp(),updatedAt:x.updatedAt||stamp()}}).filter(function(d){return d.status==='draft'});return out}
  function legacyToV14(old){var data={records:[],drafts:[],settings:{version:'1.4',migratedFrom:'legacy'}};if(!old)return data;var reviews=Array.isArray(old.reviews)?old.reviews:[];var thoughts=Array.isArray(old.thoughts)?old.thoughts:[];reviews.forEach(function(r,i){data.records.push({id:'legacy_r_'+i+'_'+Date.now(),type:'review',date:r.date||today(),time:r.time||((r.createdAt||'').slice(11,16))||nowTime(),mood:Number(r.mood)||3,energy:Number(r.energy)||3,tags:Array.isArray(r.tags)?r.tags:[],fields:{done:r.done||'',valuable:r.valuable||'',job:r.job||'',ability:r.ability||'',body:r.body||'',emotion:r.emotion||'',low:r.low||'',tomorrow:r.tomorrow||''},createdAt:r.createdAt||stamp(),uploadedAt:r.updatedAt||r.createdAt||stamp(),sourceDraftId:null})});thoughts.forEach(function(t,i){data.records.push({id:'legacy_t_'+i+'_'+Date.now(),type:'thought',date:t.date||today(),time:t.time||nowTime(),thoughtType:t.type||'行动线索',fields:{text:t.text||'',signal:t.signal||'',next:t.next||''},createdAt:t.createdAt||stamp(),uploadedAt:t.createdAt||stamp(),sourceDraftId:null})});return data}
  function load(){var data=readJSON(KEY,null);if(!data){for(var i=0;i<LEGACY_KEYS.length;i++){var old=readJSON(LEGACY_KEYS[i],null);if(old){data=legacyToV14(old);break}}}state=normalize(data||{records:[],drafts:[],settings:{version:'1.4'}});migrateLegacyDrafts();saveState()}
  function migrateLegacyDrafts(){var seen={};state.drafts.forEach(function(d){seen[d.date+'_'+d.type]=1});try{for(var i=0;i<localStorage.length;i++){var k=localStorage.key(i);for(var j=0;j<LEGACY_FORM_PREFIXES.length;j++){var p=LEGACY_FORM_PREFIXES[j];if(k&&k.indexOf(p)===0){var f=readJSON(k,null);if(f&&f.date&&!seen[f.date+'_review']){state.drafts.push({id:uid('draft_legacy'),type:'review',date:f.date,time:f.time||nowTime(),mood:Number(f.mood)||3,energy:Number(f.energy)||3,tags:Array.isArray(f.tags)?f.tags:[],fields:{done:f.done||'',valuable:f.valuable||'',job:f.job||'',ability:f.ability||'',body:f.body||'',emotion:f.emotion||'',low:f.low||'',tomorrow:f.tomorrow||''},status:'draft',createdAt:f.createdAt||stamp(),updatedAt:f.updatedAt||f.createdAt||stamp()});seen[f.date+'_review']=1}}}}}catch(e){}
  }
  function saveState(){state.settings.version='1.4.7';state.settings.updatedAt=stamp();return writeJSON(KEY,state)}
  function reviewIds(){return ['r_done','r_valuable','r_job','r_ability','r_body','r_emotion','r_low','r_tomorrow']}
  function thoughtIds(){return ['t_text','t_signal','t_next']}
  function setMode(mode){currentMode=mode;qsa('.mode').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-mode')===mode)});$('review_form').classList.toggle('hidden',mode!=='review');$('review_meta').classList.toggle('hidden',mode!=='review');$('thought_form').classList.toggle('hidden',mode!=='thought');updateDraftStatus()}
  function updateUI(){qsa('[data-seg="mood"]').forEach(function(b){b.classList.toggle('active',Number(b.getAttribute('data-val'))===mood)});qsa('[data-seg="energy"]').forEach(function(b){b.classList.toggle('active',Number(b.getAttribute('data-val'))===energy)});qsa('.chip[data-tag]').forEach(function(c){c.classList.toggle('active',selectedTags.indexOf(c.getAttribute('data-tag'))>=0)})}
  function currentFields(){if(currentMode==='review'){return {done:$('r_done').value,valuable:$('r_valuable').value,job:$('r_job').value,ability:$('r_ability').value,body:$('r_body').value,emotion:$('r_emotion').value,low:$('r_low').value,tomorrow:$('r_tomorrow').value}}return {text:$('t_text').value,signal:$('t_signal').value,next:$('t_next').value}}
  function hasContent(fields){return Object.keys(fields||{}).some(function(k){return String(fields[k]||'').trim()})}
  function collectDraft(){return {id:currentDraftId||uid('draft'),type:currentMode,date:$('date').value||today(),time:$('time').value||nowTime(),mood:mood,energy:energy,tags:selectedTags.slice(),thoughtType:$('t_type').value||'行动线索',fields:currentFields(),status:'draft',createdAt:currentDraftId?(findDraft(currentDraftId)||{}).createdAt||stamp():stamp(),updatedAt:stamp()}}
  function findDraft(id){return state.drafts.find(function(d){return d.id===id})}
  function loadDraft(d){currentDraftId=d.id;setMode(d.type);$('date').value=d.date||today();$('time').value=d.time||nowTime();mood=Number(d.mood)||3;energy=Number(d.energy)||3;selectedTags=Array.isArray(d.tags)?d.tags.slice():[];$('t_type').value=d.thoughtType||'行动线索';reviewIds().forEach(function(id){$(id).value=(d.fields&&d.fields[id.replace('r_','')])||''});$('t_text').value=(d.fields&&d.fields.text)||'';$('t_signal').value=(d.fields&&d.fields.signal)||'';$('t_next').value=(d.fields&&d.fields.next)||'';updateUI();updateDraftStatus();switchView('capture')}
  function clearForm(){currentDraftId=null;$('date').value=today();$('time').value=nowTime();mood=3;energy=3;selectedTags=[];$('t_type').value='行动线索';reviewIds().forEach(function(id){$(id).value=''});thoughtIds().forEach(function(id){$(id).value=''});updateUI();updateDraftStatus()}
  function updateDraftStatus(){var txt=currentDraftId?'当前草稿：'+currentDraftId.slice(0,12)+'｜已自动保护，建议手动点“存为草稿”':'当前：新建草稿｜输入中会自动暂存，完成后可上传';$('current_draft_status').textContent=txt}
  function saveDraft(manual){var d=collectDraft();if(!hasContent(d.fields)&&manual){toast('内容为空，未保存');return null}var idx=state.drafts.findIndex(function(x){return x.id===d.id});if(idx>=0)state.drafts[idx]=d;else state.drafts.unshift(d);currentDraftId=d.id;saveState();updateDraftStatus();renderDrafts();renderCalendar();renderStats();if(manual)toast('已存为草稿');return d}
  function autoDraft(){clearTimeout(timer);timer=setTimeout(function(){var fields=currentFields();if(hasContent(fields))saveDraft(false)},350)}
  function uploadDraft(d,fromButton){if(!d)d=saveDraft(false);if(!d||!hasContent(d.fields)){toast('内容为空，不能上传');return}var rec={id:uid('rec'),type:d.type,date:d.date||today(),time:d.time||nowTime(),mood:d.mood,energy:d.energy,tags:Array.isArray(d.tags)?d.tags:[],thoughtType:d.thoughtType||'行动线索',fields:JSON.parse(JSON.stringify(d.fields||{})),createdAt:d.createdAt||stamp(),uploadedAt:stamp(),sourceDraftId:d.id};state.records.unshift(rec);state.drafts=state.drafts.filter(function(x){return x.id!==d.id});if(currentDraftId===d.id)clearForm();saveState();renderDrafts();renderCalendar();renderStats();toast('已上传到历史库');return rec}
  function recordToDraft(r){var d={id:uid('draft_from_record'),type:r.type,date:r.date,time:r.time,mood:r.mood||3,energy:r.energy||3,tags:Array.isArray(r.tags)?r.tags.slice():[],thoughtType:r.thoughtType||'行动线索',fields:JSON.parse(JSON.stringify(r.fields||{})),status:'draft',createdAt:stamp(),updatedAt:stamp()};state.drafts.unshift(d);saveState();loadDraft(d);toast('已复制为草稿，可继续编辑')}
  function reviewPrompt(x){var f=x.fields||{};return '【Phoenix 每日复盘】\n日期：'+x.date+(x.time?' '+x.time:'')+'\n情绪：'+(x.mood||3)+'/5｜精力：'+(x.energy||3)+'/5\n标签：'+((x.tags&&x.tags.length)?x.tags.join('、'):'无')+'\n\n1. 今天做了什么：\n'+nl(f.done)+'\n\n2. 今天真正有价值的动作：\n'+nl(f.valuable)+'\n\n3. 求职 / 面试 / 投递推进：\n'+nl(f.job)+'\n\n4. 案例库 / 专业能力 / 英语：\n'+nl(f.ability)+'\n\n5. 身体 / 健身 / 作息：\n'+nl(f.body)+'\n\n6. 情绪 / 家庭边界 / 社交状态：\n'+nl(f.emotion)+'\n\n7. 低价值消耗：\n'+nl(f.low)+'\n\n8. 明天最重要的3件事：\n'+nl(f.tomorrow)+'\n\n请你基于以上内容，按“行动质量、低价值消耗、情绪信号、是否偏离求职跃迁主线、明天1-3个关键动作”帮我复盘，并直接给出可执行建议。'}
  function thoughtPrompt(x){var f=x.fields||{};return '【Phoenix 随机想法】\n日期：'+x.date+' '+(x.time||'')+'\n分类：'+(x.thoughtType||'未分类')+'\n\n1. 原始想法：\n'+nl(f.text)+'\n\n2. 背后的真实信号：\n'+nl(f.signal)+'\n\n3. 下一步处理：\n'+nl(f.next)+'\n\n请你帮我判断这个想法属于行动线索、内容素材、情绪信号还是低价值噪音，并给我一个可执行的下一步。'}
  function promptFor(x){return x.type==='review'?reviewPrompt(x):thoughtPrompt(x)}
  function switchView(id){qsa('.tab').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-view')===id)});qsa('.view').forEach(function(v){v.classList.toggle('active',v.id===id)});if(id==='drafts')renderDrafts();if(id==='calendar')renderCalendar();if(id==='export')renderStats()}
  function renderDrafts(){var box=$('draft_list');if(!box)return;var arr=state.drafts.slice().sort(function(a,b){return (b.updatedAt||'').localeCompare(a.updatedAt||'')});if(!arr.length){box.innerHTML='<div class="empty">暂无草稿。未完成内容请先点“存为草稿”。</div>';return}box.innerHTML=arr.map(function(d,i){var f=d.fields||{};var body=d.type==='review'?(f.valuable||f.done||f.job||'未填写'):(f.text||'未填写');return '<div class="item"><div class="between"><div><div class="item-title">'+(d.type==='review'?'每日复盘草稿':'随机想法草稿')+'</div><div class="small">'+esc(d.date+' '+(d.time||'')+'｜更新：'+String(d.updatedAt||'').slice(0,16).replace('T',' '))+'</div></div><div class="row"><button class="chip blue" data-edit-draft="'+i+'">继续编辑</button><button class="chip" data-upload-draft="'+i+'">上传</button><button class="chip" data-del-draft="'+i+'">删除</button></div></div><div class="small" style="margin-top:8px">'+esc(String(body).slice(0,150))+'</div></div>'}).join('');box.querySelectorAll('[data-edit-draft]').forEach(function(b){b.onclick=function(){loadDraft(arr[Number(b.getAttribute('data-edit-draft'))])}});box.querySelectorAll('[data-upload-draft]').forEach(function(b){b.onclick=function(){uploadDraft(arr[Number(b.getAttribute('data-upload-draft'))],true)}});box.querySelectorAll('[data-del-draft]').forEach(function(b){b.onclick=function(){var d=arr[Number(b.getAttribute('data-del-draft'))];if(confirm('删除这个草稿？')){state.drafts=state.drafts.filter(function(x){return x.id!==d.id});if(currentDraftId===d.id)clearForm();saveState();renderDrafts();renderStats();toast('已删除草稿')}}})}
  function recordsForDate(date,type){return state.records.filter(function(r){return r.date===date&&(type==='all'||!type||r.type===type)}).sort(function(a,b){return ((a.time||'')+(a.uploadedAt||'')).localeCompare((b.time||'')+(b.uploadedAt||''))})}
  function renderCalendar(){var date=$('cal_date').value||today();var type=$('cal_type').value||'all';var arr=recordsForDate(date,type);var drafts=state.drafts.filter(function(d){return d.date===date});$('cal_count').textContent=arr.length+' 条正式记录';$('cal_draft_count').textContent=drafts.length+' 个草稿';var box=$('calendar_list');if(!arr.length){box.innerHTML='<div class="empty">这一天暂无正式记录。未完成内容可去“草稿箱”查看。</div>';return}box.innerHTML=arr.map(function(r,i){var f=r.fields||{};var body=r.type==='review'?(f.valuable||f.done||f.job||'未填写'):(f.text||'未填写');var title=r.type==='review'?'每日复盘':'随机想法 · '+(r.thoughtType||'未分类');return '<div class="item"><div class="between"><div><div class="item-title">'+esc(title)+'</div><div class="small">'+esc(r.date+' '+(r.time||'')+'｜上传：'+String(r.uploadedAt||'').slice(0,16).replace('T',' '))+'</div></div><div class="row"><button class="chip blue" data-copy-rec="'+i+'">复制</button><button class="chip" data-edit-rec="'+i+'">转为草稿</button></div></div><div class="small" style="margin-top:8px">'+esc(String(body).slice(0,200))+'</div></div>'}).join('');box.querySelectorAll('[data-copy-rec]').forEach(function(b){b.onclick=function(){copyText(promptFor(arr[Number(b.getAttribute('data-copy-rec'))]))}});box.querySelectorAll('[data-edit-rec]').forEach(function(b){b.onclick=function(){recordToDraft(arr[Number(b.getAttribute('data-edit-rec'))])}})}
  function setDateBy(delta){var d=new Date(($('cal_date').value||today())+'T00:00:00');d.setDate(d.getDate()+delta);$('cal_date').value=d.toISOString().slice(0,10);renderCalendar()}
  function startOfWeek(dateStr){var d=new Date(dateStr+'T00:00:00');var day=d.getDay()||7;d.setDate(d.getDate()-day+1);return d.toISOString().slice(0,10)}
  function setRange(kind){var end=today(),start=today();if(kind==='week'){start=startOfWeek(end)}else if(kind==='7'){var d=new Date(end+'T00:00:00');d.setDate(d.getDate()-6);start=d.toISOString().slice(0,10)}else if(kind==='month'){start=end.slice(0,8)+'01'}$('export_start').value=start;$('export_end').value=end}
  function rangeData(){var s=$('export_start').value||today(),e=$('export_end').value||today();var recs=state.records.filter(function(r){return r.date>=s&&r.date<=e}).sort(function(a,b){return (a.date+' '+(a.time||'')).localeCompare(b.date+' '+(b.time||''))});var drafts=$('include_drafts').checked?state.drafts.filter(function(d){return d.date>=s&&d.date<=e}).sort(function(a,b){return (a.date+' '+(a.time||'')).localeCompare(b.date+' '+(b.time||''))}):[];return {start:s,end:e,records:recs,drafts:drafts}}
  function exportText(){var d=rangeData();var reviews=d.records.filter(function(x){return x.type==='review'}),thoughts=d.records.filter(function(x){return x.type==='thought'});var avg=function(arr,k){return arr.length?(arr.reduce(function(s,x){return s+(Number(x[k])||0)},0)/arr.length).toFixed(1):'无'};var txt='【Phoenix 阶段数据导出】\n范围：'+d.start+' 至 '+d.end+'\n正式记录：'+d.records.length+'｜复盘：'+reviews.length+'｜想法：'+thoughts.length+'｜草稿：'+d.drafts.length+'\n平均情绪：'+avg(reviews,'mood')+'/5｜平均精力：'+avg(reviews,'energy')+'/5\n\n一、正式历史记录\n';txt+=d.records.length?d.records.map(function(r){return '\n---\n'+promptFor(r)}).join('\n'):'未记录';if(d.drafts.length){txt+='\n\n二、未完成草稿\n'+d.drafts.map(function(x){return '\n---\n【草稿】\n'+promptFor(x)}).join('\n')}txt+='\n\n请你基于以上数据做阶段复盘：\n1. 提炼真正有效的行动；\n2. 识别低价值消耗和反复出现的情绪噪音；\n3. 判断我是否靠近技术采购/战略采购/海外供应链主线；\n4. 给出下一阶段最重要的3个动作；\n5. 输出一份可直接放进 Apple 备忘录的总结。';return txt}
  function renderStats(){var days={};state.records.forEach(function(r){days[r.date]=1});$('stat_records').textContent=state.records.length;$('stat_drafts').textContent=state.drafts.length;$('stat_days').textContent=Object.keys(days).length;$('storage_status').textContent=okLS()?'本机保存可用：数据保存在当前浏览器 localStorage。':'当前环境禁止本地保存，请关闭无痕模式或换 Safari。'}
  function bind(){
    qsa('.tab').forEach(function(b){b.onclick=function(){switchView(b.getAttribute('data-view'))}});
    qsa('.mode').forEach(function(b){b.onclick=function(){setMode(b.getAttribute('data-mode'));autoDraft()}});
    qsa('[data-seg]').forEach(function(b){b.onclick=function(){var seg=b.getAttribute('data-seg'),v=Number(b.getAttribute('data-val'));if(seg==='mood')mood=v;else energy=v;updateUI();autoDraft()}});
    qsa('.chip[data-tag]').forEach(function(c){c.onclick=function(){var tag=c.getAttribute('data-tag'),i=selectedTags.indexOf(tag);if(i>=0)selectedTags.splice(i,1);else selectedTags.push(tag);updateUI();autoDraft()}});
    ['date','time','t_type'].concat(reviewIds(),thoughtIds()).forEach(function(id){$(id).addEventListener('input',autoDraft);$(id).addEventListener('change',autoDraft)});
    $('save_draft').onclick=function(){saveDraft(true)};$('upload_draft').onclick=function(){uploadDraft(saveDraft(false),true)};$('new_blank').onclick=function(){if(confirm('新建空白草稿？当前未保存内容请先存为草稿。'))clearForm()};
    $('copy_current').onclick=function(){var d=collectDraft();$('copy_output').textContent=promptFor(d);$('copy_card').classList.remove('hidden')};$('copy_output_btn').onclick=function(){copyText($('copy_output').textContent||promptFor(collectDraft()))};
    $('cal_date').onchange=renderCalendar;$('cal_type').onchange=renderCalendar;$('prev_day').onclick=function(){setDateBy(-1)};$('next_day').onclick=function(){setDateBy(1)};$('today_day').onclick=function(){$('cal_date').value=today();renderCalendar()};
    $('range_week').onclick=function(){setRange('week')};$('range_7').onclick=function(){setRange('7')};$('range_month').onclick=function(){setRange('month')};
    $('make_export').onclick=function(){var txt=exportText();$('export_output').textContent=txt;$('export_card').classList.remove('hidden')};$('copy_export').onclick=function(){copyText($('export_output').textContent||exportText())};$('download_txt').onclick=function(){download('phoenix-export-'+($('export_start').value||today())+'_'+($('export_end').value||today())+'.txt',exportText(),'text/plain')};$('download_json').onclick=function(){download('phoenix-backup-'+today()+'.json',JSON.stringify(state,null,2),'application/json')};
    $('import_file').onchange=function(e){var f=e.target.files&&e.target.files[0];if(!f)return;var r=new FileReader();r.onload=function(){try{var data=normalize(JSON.parse(r.result));state=data;saveState();renderDrafts();renderCalendar();renderStats();toast('导入成功')}catch(err){toast('导入失败：JSON格式不对')}};r.readAsText(f)};
    $('clear_all').onclick=function(){if(confirm('确认清空全部本地数据？请先导出 JSON 备份。')){state={records:[],drafts:[],settings:{version:'1.4.7'}};saveState();clearForm();renderDrafts();renderCalendar();renderStats();toast('已清空')}};
  }
  function init(){if(!okLS())toast('当前环境禁止本地保存');load();$('today_text').textContent=today();$('date').value=today();$('time').value=nowTime();$('cal_date').value=today();setRange('week');bind();setMode('review');updateUI();renderDrafts();renderCalendar();renderStats()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
